FROM python:3.8
# specify the current wd
WORKDIR /user/src/app

# migrate all local files in the computer to the remote container
ENV APP /app
WORKDIR $APP_HOME
COPY . ./

# Use pip to install the project requirements
RUN python-pip install Flask gunicorn

# Run the web server upon startup with eight threads 
CMD exe gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
